/**
 * The public catalog drives every game shelf and route in the portal.
 * Add future games here instead of hard-coding homepage sections.
 */
export const gameCatalog = [
  {
    id: 'game-001',
    slug: 'orbit-break',
    title: 'Orbit Break',
    featured: true,
    artVariant: 'orbit',
    eyebrow: 'Now playable',
    summary: 'Reverse your orbit. Read the warning lines. Survive the pattern.',
    description: 'A compact one-action survival game built for quick runs and clean restarts.',
    route: '/games/orbit-break',
    embedBase: '/games/orbit-break/embed/',
    embedPath: '/games/orbit-break/embed/index.html',
    controls: ['Space', 'Click', 'Tap'],
    tags: ['Arcade', 'One action', 'Local best score'],
    accent: '#20e9ff',
    accentAlt: '#ff2caa',
    status: 'Playable',
  },
  {
    id: 'game-002',
    slug: 'reactor-stack',
    title: 'Reactor Stack',
    featured: false,
    artVariant: 'title',
    eyebrow: 'Containment puzzle',
    summary: 'Merge energy cells, manage heat, and stabilize a damaged reactor.',
    description: 'A portrait-first spatial puzzle where every valid move adds pressure to the core.',
    route: '/games/reactor-stack',
    embedBase: '/games/reactor-stack/embed/',
    embedPath: '/games/reactor-stack/embed/index.html',
    controls: ['Drag a cell', 'Tap source + destination', 'Mute sound'],
    tags: ['Puzzle', 'Strategy', 'Portrait-first'],
    accent: '#ffb43c',
    accentAlt: '#ee5d5d',
    status: 'Playable',
  },
  {
    id: 'game-003',
    slug: 'last-relay',
    title: 'Last Relay',
    featured: false,
    artVariant: 'title',
    eyebrow: 'Lane defense',
    summary: 'Place defences, launch waves, and protect the final communications relay.',
    description: 'A landscape-first three-lane strategy game with ten escalating waves.',
    route: '/games/last-relay',
    embedBase: '/games/last-relay/embed/',
    embedPath: '/games/last-relay/embed/index.html',
    controls: ['Select a lane', 'Choose Rapid or Heavy', 'Launch / pause'],
    tags: ['Strategy', 'Tower defense', 'Landscape-first'],
    accent: '#7ce8ff',
    accentAlt: '#7386ff',
    status: 'Playable',
  },
  {
    id: 'game-004',
    slug: 'station-quartermaster',
    title: 'Station Quartermaster',
    featured: false,
    artVariant: 'title',
    eyebrow: 'Station management',
    summary: 'Assign crew, balance vital resources, and survive ten deterministic days.',
    description: 'A compact resource-management game where each staffing choice changes tomorrow.',
    route: '/games/station-quartermaster',
    embedBase: '/games/station-quartermaster/embed/',
    embedPath: '/games/station-quartermaster/embed/index.html',
    controls: ['Select crew + module', 'Use resupply', 'End day'],
    tags: ['Strategy', 'Management', 'Local save'],
    accent: '#9ee17b',
    accentAlt: '#44bfa3',
    status: 'Playable',
  },
  {
    id: 'game-005',
    slug: 'signal-below',
    title: 'Signal Below',
    featured: false,
    artVariant: 'title',
    eyebrow: 'Narrative mystery',
    summary: 'Follow an impossible transmission through an abandoned relay station.',
    description: 'An atmospheric sci-fi mystery of rooms, clues, responses, and a final decision.',
    route: '/games/signal-below',
    embedBase: '/games/signal-below/embed/',
    embedPath: '/games/signal-below/embed/index.html',
    controls: ['Click scene markers', 'Tap responses', 'Explore rooms'],
    tags: ['Narrative', 'Adventure', 'Local checkpoint'],
    accent: '#8ad6cf',
    accentAlt: '#b899e8',
    status: 'Playable',
  },
];

/** Build-only source locations, resolved from the portal root. */
export const gameBuilds = {
  'orbit-break': {
    sourceDir: 'games/orbit-break',
  },
  'reactor-stack': {
    sourceDir: 'games/reactor-stack',
  },
  'last-relay': {
    sourceDir: 'games/last-relay',
  },
  'station-quartermaster': {
    sourceDir: 'games/station-quartermaster',
  },
  'signal-below': {
    sourceDir: 'games/signal-below',
  },
};
