import type Phaser from 'phaser';
import { clampConfig, copyConfig, type RuntimeConfig } from './config.ts';
import { cellCount, evaluate, legalDestinations, type TurnController } from './rules.ts';
import { clearReactorStorage, readBest, readScores } from './storage.ts';

type Api = { locked(): boolean; menu(): boolean; controller: TurnController; game: Phaser.Game; scene: () => { effects: number; gesture: { selected: number | null }; layoutBoard(): void; render(): void; hud(): void; message(value: string): void; clean(): void; tweenCount(): number; toggleDebug(key: 'indices'|'legal'|'selection'|'geometry'|'bounds'): boolean }; audio: { muted: boolean; volume: number; setMuted(value: boolean): void; play(kind: 'move'|'merge'|'win'|'fail'|'warning', tier?: number): void }; sessionLog: unknown[]; startRun(): void; showScores(): void; message(value: string): void; runDuration(): number; render(): void; resetDefaults(): void; recordCompletion(): void };
const number = (label: string, value: number, onChange: (next: number) => void, note = 'LIVE') => `<label class="dev-field"><span>${label}<em>${note}</em></span><input type="number" value="${value}" step="${Number.isInteger(value) ? 1 : .01}" data-field="${label}"></label>`;
const section = (title:string, body:string) => `<details class="dev-section" open><summary>${title}</summary><div class="dev-section-body">${body}</div></details>`;
const download = (name:string, type:string, content:string) => { const url=URL.createObjectURL(new Blob([content],{type})); const link=document.createElement('a'); link.href=url;link.download=name;link.click();setTimeout(()=>URL.revokeObjectURL(url),0); };

export function mountDevPanel(api: Api) {
  const root=document.createElement('aside'); root.id='dev-panel'; root.hidden=true; root.innerHTML=`<header><strong>REACTOR STACK DEV</strong><button data-action="close">×</button></header><div class="dev-scroll"><div id="reactor-ads-dev"></div><div id="dev-scroll"></div></div>`; document.body.append(root);
  let fps=0, average=0, worst=0, last=performance.now(), frames=0, elapsed=0;
  const tick=(now:number)=>{const delta=now-last;last=now;fps=1000/Math.max(1,delta);average=average?average*.95+fps*.05:fps;worst=Math.max(worst,delta);frames++;elapsed+=delta;if(elapsed>1000){worst=0;elapsed=0;}requestAnimationFrame(tick);};requestAnimationFrame(tick);
  const draw=()=>{
    const cfg=api.controller.runtimeConfig, active=api.controller.activeConfig, state=api.controller.state, shell=document.getElementById('game-shell')!, board=document.getElementById('board')!, rect=board.getBoundingClientRect(), mode=shell.dataset.layout??'portrait', selected=api.scene().gesture.selected, legal=selected===null?[]:legalDestinations(state.board,selected,active);
    const rows:{label:string;value:number;target:'runtime'|'active';note?:string}[]=[
      {label:'Grid Width',value:cfg.gridWidth,target:'runtime',note:'RESTART REQUIRED'}, {label:'Grid Height',value:cfg.gridHeight,target:'runtime',note:'RESTART REQUIRED'}, {label:'Initial Cell Count',value:cfg.initialCellCount,target:'runtime',note:'NEXT RUN'},
      {label:'Initial Tier I Weight',value:cfg.initialTierWeights[0]*100,target:'runtime',note:'NEXT RUN %'}, {label:'Initial Tier II Weight',value:cfg.initialTierWeights[1]*100,target:'runtime',note:'NEXT RUN %'},
      {label:'Spawn Tier I Weight',value:cfg.spawnTierWeights[0]*100,target:'active',note:'LIVE %'}, {label:'Spawn Tier II Weight',value:cfg.spawnTierWeights[1]*100,target:'active',note:'LIVE %'},
      {label:'Maximum Heat',value:cfg.heatMaximum,target:'active'}, {label:'Heat Per Accepted Move',value:cfg.baseTurnHeat,target:'active'}, {label:'Warning Threshold',value:cfg.heatWarningThreshold,target:'active'},
      {label:'Cool Core Uses / Run',value:cfg.coolCoreUses,target:'runtime',note:'NEXT RUN'}, {label:'Cool Core Amount',value:cfg.coolCoreAmount,target:'active'}, {label:'Stability Target',value:cfg.stabilityTarget,target:'active'},
      {label:'Tier II Cooling',value:cfg.mergeHeatReductionByTier[2],target:'active'}, {label:'Tier III Cooling',value:cfg.mergeHeatReductionByTier[3],target:'active'}, {label:'Tier IV Cooling',value:cfg.mergeHeatReductionByTier[4],target:'active'}, {label:'Tier V Cooling',value:cfg.mergeHeatReductionByTier[5],target:'active'},
      {label:'Tier II Stability',value:cfg.stabilityRewardByTier[2],target:'active'}, {label:'Tier III Stability',value:cfg.stabilityRewardByTier[3],target:'active'}, {label:'Tier IV Stability',value:cfg.stabilityRewardByTier[4],target:'active'}, {label:'Tier V Stability',value:cfg.stabilityRewardByTier[5],target:'active'},
      {label:'Tier II Score',value:cfg.scoreRewardByTier[2],target:'active'}, {label:'Tier III Score',value:cfg.scoreRewardByTier[3],target:'active'}, {label:'Tier IV Score',value:cfg.scoreRewardByTier[4],target:'active'}, {label:'Tier V Score',value:cfg.scoreRewardByTier[5],target:'active'},
      {label:'Upgrade Uses / Run',value:cfg.upgradeUses,target:'runtime',note:'NEXT RUN'}, {label:'Upgrade Max Tier',value:cfg.upgradeMaximumTier,target:'active'}, {label:'Move Duration',value:cfg.moveDuration,target:'active'}, {label:'Merge Duration',value:cfg.mergeDuration,target:'active'}, {label:'Spawn Duration',value:cfg.spawnDuration,target:'active'}, {label:'SFX Volume',value:cfg.sfxVolume,target:'active'}];
    const fields=(prefix:string)=>rows.filter(row=>row.label.startsWith(prefix)).map(row=>number(row.label,row.value,()=>{},row.note)).join('');
    document.getElementById('dev-scroll')!.innerHTML=
      section('RUNTIME',`<div class="dev-live">Phase <b>${api.controller.phase}</b> · Moves <b>${state.moves}</b> · Score <b>${state.score}</b> · Elapsed wall time <b>${api.runDuration()}s</b><br>Heat <b>${state.heat}/${active.heatMaximum}</b> · Stability <b>${state.stability}/${active.stabilityTarget}</b><br>Occupied <b>${state.board.filter(Boolean).length}/${cellCount(active)}</b> · Legal Actions <b>${state.board.reduce((n,_,i)=>n+legalDestinations(state.board,i,active).length,0)}</b><br>Result <b>${state.result??'—'}</b> · ${state.reason||'No failure'}<br>Cool Core <b>${state.coolCoreRemaining}</b> · Upgrade <b>${state.upgradeRemaining}</b></div><div class="dev-actions"><button data-action="restart">Restart Run</button><button data-action="menu">Return to Menu</button></div>`)+
      section('VIEWPORT',`<div class="dev-live">Container <b>${shell.clientWidth} × ${shell.clientHeight}</b><br>Mode <b>${mode}</b> · Aspect <b>${(shell.clientWidth/Math.max(1,shell.clientHeight)).toFixed(2)}</b> · DPR <b>${devicePixelRatio}</b><br>Board CSS <b>${Math.round(rect.width)} × ${Math.round(rect.height)}</b> · Canvas <b>${Math.round(api.game.scale.width)} × ${Math.round(api.game.scale.height)}</b><br>Cell size <b>${Math.round(rect.width/active.gridWidth)}</b> · Support <b>${mode==='constrained'?'Constrained':'Supported'}</b></div>`)+
      section('PERFORMANCE',`<div class="dev-live">FPS <b>${fps.toFixed(0)}</b> · Rolling <b>${average.toFixed(0)}</b><br>Frame <b>${(1000/Math.max(1,fps)).toFixed(1)}ms</b> · Worst recent <b>${worst.toFixed(1)}ms</b><br>Cells rendered <b>${state.board.filter(Boolean).length}</b> · Tweens <b>${api.scene().tweenCount()}</b> · Effects <b>${api.scene().effects}</b></div>`)+
      section('BOARD',fields('Grid')+number('Initial Cell Count',cfg.initialCellCount,()=>{},'NEXT RUN')+`<p>Structural geometry is restart-required. Active runs keep their geometry.</p>`)+
      section('SPAWNING',fields('Initial')+fields('Spawn')+`<div class="dev-live">Last spawn: <b>${(window as any).__reactorLastSpawn??'—'}</b></div>`)+
      section('HEAT',fields('Maximum')+fields('Heat')+fields('Warning')+fields('Cool')+fields('Tier II Cooling')+fields('Tier III Cooling')+fields('Tier IV Cooling')+fields('Tier V Cooling'))+
      section('STABILITY',fields('Stability')+fields('Tier II Stability')+fields('Tier III Stability')+fields('Tier IV Stability')+fields('Tier V Stability'))+
      section('SCORE',fields('Tier II Score')+fields('Tier III Score')+fields('Tier IV Score')+fields('Tier V Score'))+
      section('POWER UPS',fields('Cool')+fields('Upgrade')+`<div class="dev-actions"><button data-action="restore-cool">Restore Cool</button><button data-action="test-cool">Use/Test Cool</button><button data-action="restore-upgrade">Restore Upgrade</button><button data-action="test-upgrade">Enter Test Mode</button></div>`)+
      section('ANIMATION / FEEL',fields('Move Duration')+fields('Merge Duration')+fields('Spawn Duration'))+
      section('AUDIO',`<label class="dev-check"><input type="checkbox" data-action="mute" ${api.audio.muted?'':'checked'}> Mute</label>`+number('SFX Volume',cfg.sfxVolume,()=>{},'LIVE')+`<div class="dev-actions">${(['move','merge','warning','win','fail'] as const).map(cue=>`<button data-cue="${cue}">${cue}</button>`).join('')}</div>`)+
      section('STORAGE',`<div class="dev-live">Current Best <b>${readBest()}</b> · Stored Runs <b>${readScores().length}</b></div><div class="dev-actions"><button data-action="view-scores">View Scores</button><button data-action="clear-scores">Clear Scores</button><button data-action="reset-data">Reset All Reactor Stack Data</button></div>`)+
      section('QA FIXTURES',`<div class="dev-actions fixture-actions">${['Fresh Run','Near Victory','Near Heat Failure','All Tiers','Near Deadlock','Full Deadlock','Power-Up Test','Force Win','Force Fail'].map(name=>`<button data-fixture="${name}">${name}</button>`).join('')}</div>`)+
      section('DEBUG',`<div class="dev-live">Selected Cell <b>${selected??'—'}</b> · Tier <b>${selected===null?'—':state.board[selected]||'—'}</b><br>Legal destinations <b>${legal.join(', ')||'—'}</b></div><div class="dev-actions"><button data-action="show-indices">Show Cell Indices</button><button data-action="show-legal">Show Legal Moves</button><button data-action="show-selection">Show Selected Cell</button><button data-action="show-geometry">Show Board Geometry</button><button data-action="show-bounds">Show Layout Bounds</button><button data-action="reevaluate">Re-evaluate Board</button></div>`)+
      section('DEV CHEATS / TESTING',`<div class="dev-actions"><button data-cheat="heat-">Heat -10</button><button data-cheat="heat+">Heat +10</button><button data-cheat="stability-">Stability -10</button><button data-cheat="stability+">Stability +10</button><button data-cheat="score">Score +100</button><button data-cheat="add">Add Random Cell</button><button data-cheat="remove">Remove Selected</button><button data-cheat="tier">Set Selected Tier</button></div>`)+
      section('SESSION LOG',`<div class="dev-live">RAM-only completed sessions: <b>${api.sessionLog.length}</b></div><div class="dev-actions"><button data-action="export-json">Export JSON</button><button data-action="export-csv">Export CSV</button><button data-action="clear-log">Clear Session Log</button></div>`)+
      section('CONFIG ACTIONS',`<div class="dev-actions"><button data-action="reset-defaults">RESET DEFAULTS</button><button data-action="copy-config">COPY CONFIG JSON</button></div><p>Tuning is memory-only. LIVE values affect the current run safely; NEXT RUN applies at start; structural changes require restart.</p>`);
    root.querySelectorAll<HTMLInputElement>('[data-field]').forEach(input=>input.onchange=()=>changeField(input.dataset.field!,Number(input.value)));
    root.querySelectorAll<HTMLButtonElement>('[data-action]').forEach(button=>button.onclick=()=>action(button.dataset.action!)); root.querySelectorAll<HTMLButtonElement>('[data-cue]').forEach(button=>button.onclick=()=>api.audio.play(button.dataset.cue as any)); root.querySelectorAll<HTMLButtonElement>('[data-fixture]').forEach(button=>button.onclick=()=>fixture(button.dataset.fixture!)); root.querySelectorAll<HTMLButtonElement>('[data-cheat]').forEach(button=>button.onclick=()=>cheat(button.dataset.cheat!));
  };
  const changeField=(label:string,value:number)=>{if(api.locked())return;const cfg=api.controller.runtimeConfig, active=api.controller.activeConfig; const assign=(target:RuntimeConfig)=>{const map:Record<string,()=>void>={ 'Grid Width':()=>target.gridWidth=value,'Grid Height':()=>target.gridHeight=value,'Initial Cell Count':()=>target.initialCellCount=value,'Initial Tier I Weight':()=>target.initialTierWeights[0]=value/100,'Initial Tier II Weight':()=>target.initialTierWeights[1]=value/100,'Spawn Tier I Weight':()=>target.spawnTierWeights[0]=value/100,'Spawn Tier II Weight':()=>target.spawnTierWeights[1]=value/100,'Maximum Heat':()=>target.heatMaximum=value,'Heat Per Accepted Move':()=>target.baseTurnHeat=value,'Warning Threshold':()=>target.heatWarningThreshold=value,'Cool Core Uses / Run':()=>target.coolCoreUses=value,'Cool Core Amount':()=>target.coolCoreAmount=value,'Stability Target':()=>target.stabilityTarget=value,'Tier II Cooling':()=>target.mergeHeatReductionByTier[2]=value,'Tier III Cooling':()=>target.mergeHeatReductionByTier[3]=value,'Tier IV Cooling':()=>target.mergeHeatReductionByTier[4]=value,'Tier V Cooling':()=>target.mergeHeatReductionByTier[5]=value,'Tier II Stability':()=>target.stabilityRewardByTier[2]=value,'Tier III Stability':()=>target.stabilityRewardByTier[3]=value,'Tier IV Stability':()=>target.stabilityRewardByTier[4]=value,'Tier V Stability':()=>target.stabilityRewardByTier[5]=value,'Tier II Score':()=>target.scoreRewardByTier[2]=value,'Tier III Score':()=>target.scoreRewardByTier[3]=value,'Tier IV Score':()=>target.scoreRewardByTier[4]=value,'Tier V Score':()=>target.scoreRewardByTier[5]=value,'Upgrade Uses / Run':()=>target.upgradeUses=value,'Upgrade Max Tier':()=>target.upgradeMaximumTier=value,'Move Duration':()=>target.moveDuration=value,'Merge Duration':()=>target.mergeDuration=value,'Spawn Duration':()=>target.spawnDuration=value,'SFX Volume':()=>target.sfxVolume=value};map[label]?.();clampConfig(target);};assign(cfg); if(!['Grid Width','Grid Height','Initial Cell Count','Initial Tier I Weight','Initial Tier II Weight','Cool Core Uses / Run','Upgrade Uses / Run'].includes(label))assign(active); api.audio.volume=active.sfxVolume; if(api.controller.state.heat>active.heatMaximum)api.controller.state.heat=active.heatMaximum; if(api.controller.state.stability>active.stabilityTarget)api.controller.state.stability=active.stabilityTarget; api.render();draw();};
  const fixture=(name:string)=>{if(api.locked())return;api.startRun();const s=api.controller.state;s.board.fill(0); if(name==='Fresh Run'){} else if(name==='Near Victory'){s.board[0]=s.board[1]=4;s.stability=Math.max(0,api.controller.activeConfig.stabilityTarget-api.controller.activeConfig.stabilityRewardByTier[5]);} else if(name==='Near Heat Failure'){s.board[0]=1;s.heat=Math.max(0,api.controller.activeConfig.heatMaximum-api.controller.activeConfig.baseTurnHeat);} else if(name==='All Tiers'){s.board.splice(0,5,1,2,3,4,5);} else if(name==='Near Deadlock'){s.board.fill(5);s.board[0]=1;s.board[1]=0;} else if(name==='Full Deadlock'){s.board.fill(5);evaluate(s,api.controller.activeConfig);} else if(name==='Power-Up Test'){s.board[0]=1;s.heat=50;s.coolCoreRemaining=1;s.upgradeRemaining=1;} else if(name==='Force Win'){s.stability=api.controller.activeConfig.stabilityTarget;evaluate(s,api.controller.activeConfig);} else if(name==='Force Fail'){s.heat=api.controller.activeConfig.heatMaximum;evaluate(s,api.controller.activeConfig);} api.render();draw();};
  const cheat=(kind:string)=>{if(api.locked())return;const s=api.controller.state,cfg=api.controller.activeConfig,selected=api.scene().gesture.selected;if(kind==='heat-')s.heat=Math.max(0,s.heat-10);if(kind==='heat+')s.heat=Math.min(cfg.heatMaximum,s.heat+10);if(kind==='stability-')s.stability=Math.max(0,s.stability-10);if(kind==='stability+')s.stability=Math.min(cfg.stabilityTarget,s.stability+10);if(kind==='score')s.score+=100;if(kind==='add'){const slot=s.board.findIndex(t=>!t);if(slot>=0)s.board[slot]=1;}if(kind==='remove'&&selected!==null)s.board[selected]=0;if(kind==='tier'&&selected!==null&&s.board[selected])s.board[selected]=Math.min(5,s.board[selected]+1);api.render();draw();};
  const action=(kind:string)=>{if(kind==='close'){root.hidden=true;return;}if(api.locked())return;if(kind==='restart')api.startRun();if(kind==='menu'){if(!api.menu())return;api.scene().clean();document.getElementById('menu-overlay')!.hidden=false;}if(kind==='restore-cool'){api.controller.state.coolGranted+=Math.max(0,api.controller.activeConfig.coolCoreUses-api.controller.state.coolCoreRemaining);api.controller.state.coolCoreRemaining=api.controller.activeConfig.coolCoreUses;}if(kind==='test-cool')api.controller.useCoolCore();if(kind==='restore-upgrade'){api.controller.state.upgradeGranted+=Math.max(0,api.controller.activeConfig.upgradeUses-api.controller.state.upgradeRemaining);api.controller.state.upgradeRemaining=api.controller.activeConfig.upgradeUses;}if(kind==='test-upgrade')api.message('Upgrade test mode: use the player Upgrade control.');if(kind==='mute'){api.audio.setMuted(!(root.querySelector('[data-action="mute"]') as HTMLInputElement).checked);}if(kind==='view-scores')api.showScores();if(kind==='clear-scores'||kind==='reset-data'){if(confirm('Clear Reactor Stack local scores only?'))clearReactorStorage();}if(kind==='show-indices')api.scene().toggleDebug('indices');if(kind==='show-legal')api.scene().toggleDebug('legal');if(kind==='show-selection')api.scene().toggleDebug('selection');if(kind==='show-geometry')api.scene().toggleDebug('geometry');if(kind==='show-bounds')api.scene().toggleDebug('bounds');if(kind==='reevaluate')api.controller.reEvaluate();if(kind==='export-json')download('reactor-stack-dev-sessions.json','application/json',JSON.stringify(api.sessionLog,null,2));if(kind==='export-csv'){const rows=(api.sessionLog as any[]).map(x=>[x.result,x.reason,x.score,x.moves,x.duration,x.peakHeat,x.stability,...x.merges,x.coolUsed,x.upgradeUsed,x.coolGranted,x.upgradeGranted].map(value=>JSON.stringify(value)).join(','));download('reactor-stack-dev-sessions.csv','text/csv',['result,reason,score,moves,elapsedWallSeconds,peakHeat,stability,merge0,merge1,merge2,merge3,merge4,merge5,coolUsed,upgradeUsed,coolGranted,upgradeGranted',...rows].join('\n'));}if(kind==='clear-log')api.sessionLog.splice(0);if(kind==='reset-defaults')api.resetDefaults();if(kind==='copy-config')void navigator.clipboard?.writeText(JSON.stringify(api.controller.runtimeConfig,null,2));api.render();draw();};
  const key=(event:KeyboardEvent)=>{if(event.ctrlKey&&event.shiftKey&&event.key.toLowerCase()==='d'){event.preventDefault();if(api.locked())return;root.hidden=!root.hidden;if(!root.hidden)draw();}};window.addEventListener('keydown',key);draw();
}
