import { copyConfig, DEFAULT_CONFIG, type RuntimeConfig } from './config.ts';
export type Phase = 'BOOT' | 'MENU' | 'PLAYING' | 'RESOLVING' | 'PAUSED' | 'RESULT'; export type Result = 'WIN' | 'FAIL' | null;
export type State = { board: number[]; heat: number; stability: number; score: number; moves: number; result: Result; reason: string; coolCoreRemaining: number; upgradeRemaining: number; mergeCounts: number[]; peakHeat: number; coolUsed: number; upgradeUsed: number; coolGranted: number; upgradeGranted: number };
export type RNG = () => number; export type Turn = { next: State; merged: boolean; tier: number; spawned: number | null; spawnTier: number | null; from: number; to: number };
export const cellCount = (config: RuntimeConfig = DEFAULT_CONFIG) => config.gridWidth * config.gridHeight;
export const emptyState = (config: RuntimeConfig = DEFAULT_CONFIG): State => ({ board: Array(cellCount(config)).fill(0), heat: 0, stability: 0, score: 0, moves: 0, result: null, reason: '', coolCoreRemaining: config.coolCoreUses, upgradeRemaining: config.upgradeUses, mergeCounts: [0, 0, 0, 0, 0, 0], peakHeat: 0, coolUsed: 0, upgradeUsed: 0, coolGranted: config.coolCoreUses, upgradeGranted: config.upgradeUses });
export const cloneState = (state: State): State => ({ ...state, board: [...state.board], mergeCounts: [...state.mergeCounts] });
export function spawn(board: number[], rng: RNG, weights: readonly number[] = DEFAULT_CONFIG.spawnTierWeights): { slot: number; tier: number } | null { const slots = board.flatMap((tier, index) => tier === 0 ? [index] : []); if (!slots.length) return null; const slot = slots[Math.min(slots.length - 1, Math.floor(rng() * slots.length))]; const total = weights.reduce((sum, weight) => sum + Math.max(0, weight), 0) || 1; let remaining = rng() * total, tier = 1; for (let index = 0; index < weights.length - 1; index++) { remaining -= Math.max(0, weights[index]); if (remaining < 0) break; tier++; } board[slot] = tier; return { slot, tier }; }
export function initialState(config: RuntimeConfig = DEFAULT_CONFIG, rng: RNG = Math.random): State { const state = emptyState(config); for (let index = 0; index < config.initialCellCount; index++) spawn(state.board, rng, config.initialTierWeights); return state; }
export function legal(board: readonly number[], from: number, to: number, config: RuntimeConfig = DEFAULT_CONFIG): boolean { if (!Number.isInteger(from) || !Number.isInteger(to) || from < 0 || to < 0 || from >= board.length || to >= board.length || !board[from]) return false; const distance = Math.abs(from % config.gridWidth - to % config.gridWidth) + Math.abs(Math.floor(from / config.gridWidth) - Math.floor(to / config.gridWidth)); return distance === 1 && (board[to] === 0 || (board[from] === board[to] && board[from] < config.tierDefinitions.length)); }
export function legalDestinations(board: readonly number[], from: number, config: RuntimeConfig = DEFAULT_CONFIG): number[] { return board.flatMap((_, to) => legal(board, from, to, config) ? [to] : []); }
export function hasLegalAction(board: readonly number[], config: RuntimeConfig = DEFAULT_CONFIG): boolean { return board.some((_, from) => legalDestinations(board, from, config).length > 0); }
export function evaluate(state: State, config: RuntimeConfig = DEFAULT_CONFIG): void { if (state.stability >= config.stabilityTarget) { state.result = 'WIN'; state.reason = 'Reactor stabilized'; } else if (state.heat >= config.heatMaximum) { state.result = 'FAIL'; state.reason = 'Critical heat exceeded'; } else if (!hasLegalAction(state.board, config)) { state.result = 'FAIL'; state.reason = 'Containment grid locked'; } }
export function resolve(state: State, from: number, to: number, config: RuntimeConfig = DEFAULT_CONFIG, rng: RNG = Math.random): Turn | null { if (state.result || !legal(state.board, from, to, config)) return null; const next = cloneState(state), merged = next.board[to] !== 0; const tier = next.board[from] + (merged ? 1 : 0); next.board[from] = 0; next.board[to] = tier; next.moves++; next.heat = Math.max(0, Math.min(config.heatMaximum, next.heat + config.baseTurnHeat - (merged ? config.mergeHeatReductionByTier[tier] : 0))); next.peakHeat = Math.max(next.peakHeat, next.heat); if (merged) { next.stability = Math.min(config.stabilityTarget, next.stability + config.stabilityRewardByTier[tier]); next.score += config.scoreRewardByTier[tier]; next.mergeCounts[tier]++; } evaluate(next, config); const spawned = next.result ? null : spawn(next.board, rng, config.spawnTierWeights); if (!next.result) evaluate(next, config); return { next, merged, tier, spawned: spawned?.slot ?? null, spawnTier: spawned?.tier ?? null, from, to }; }
export function coolCore(state: State, config: RuntimeConfig = DEFAULT_CONFIG): State | null { if (state.result || state.coolCoreRemaining <= 0 || state.heat <= 0) return null; const next = cloneState(state); next.coolCoreRemaining--; next.coolUsed++; next.heat = Math.max(0, next.heat - config.coolCoreAmount); return next; }
export function upgrade(state: State, target: number, config: RuntimeConfig = DEFAULT_CONFIG): State | null { if (state.result || state.upgradeRemaining <= 0 || !Number.isInteger(target) || target < 0 || target >= state.board.length) return null; const tier = state.board[target]; if (!tier || tier > config.upgradeMaximumTier || tier >= config.tierDefinitions.length) return null; const next = cloneState(state); next.board[target]++; next.upgradeRemaining--; next.upgradeUsed++; return next; }
export class TurnController { phase: Phase = 'BOOT'; state: State; readonly runtimeConfig: RuntimeConfig; activeConfig: RuntimeConfig; private rng: RNG; constructor(rng: RNG = Math.random, runtimeConfig: RuntimeConfig = copyConfig()) { this.rng = rng; this.runtimeConfig = runtimeConfig; this.activeConfig = copyConfig(runtimeConfig); this.state = emptyState(this.activeConfig); } start() { this.activeConfig = copyConfig(this.runtimeConfig); this.state = initialState(this.activeConfig, this.rng); this.phase = 'PLAYING'; } setMenu() { this.phase = 'MENU'; } pause() { if (this.phase === 'PLAYING') this.phase = 'PAUSED'; } resume() { if (this.phase === 'PAUSED') this.phase = 'PLAYING'; } act(from: number, to: number) { if (this.phase !== 'PLAYING') return null; const turn = resolve(this.state, from, to, this.activeConfig, this.rng); if (turn) { this.state = turn.next; this.phase = 'RESOLVING'; } return turn; } useCoolCore() { if (this.phase !== 'PLAYING') return null; const next = coolCore(this.state, this.activeConfig); if (next) this.state = next; return next; } useUpgrade(target: number) { if (this.phase !== 'PLAYING') return null; const next = upgrade(this.state, target, this.activeConfig); if (next) this.state = next; return next; } finish() { if (this.phase === 'RESOLVING') this.phase = this.state.result ? 'RESULT' : 'PLAYING'; } reEvaluate() { evaluate(this.state, this.activeConfig); if (this.state.result) this.phase = 'RESULT'; return this.state.result; } }
